baseURL = 'https://fuuuzz.github.io'
languageCode = 'fr-fr'
title = 'Benoit Paquier'
theme = 'minimalist'

[params]
  # homepage
  mainTitle = '👋 Benoit Paquier'
  description = "Développeur web depuis 2015, j'ai travaillé en France et au Canada sur divers projets techniques et fonctionnels. Autonome, rigoureux et communicant, je contribue efficacement en équipe, en favorisant un environnement de travail positif et innovant."
  
  #socials
  [[params.social]]
    name = "github"
    link = "https://github.com/fuuuzz"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/benoit-paquier"
  [[params.social]]
    name = "email"
    link = "benoit.paquier@ik.me"  # no need for "mailto:" in the head

[caches]
  [caches.images]
    dir = ':cacheDir/images'
