baseURL = 'https://fuuuzz.github.io'
languageCode = 'fr-fr'
title = 'Benoit Paquier'
theme = 'minimalist'

[params]
  # homepage
  mainTitle = '👋 Benoit Paquier'
  
  #socials
  [[params.social]]
    name = "github"
    link = "https://github.com/fuuuzz"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/benoit-paquier"
  [[params.social]]
    name = "email"
    link = "benoit.paquier@ik.me"  # no need for "mailto:" in the head

[caches]
  [caches.images]
    dir = ':cacheDir/images'
